# Generated by Django 5.2.12 on 2026-03-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
